#!/usr/bin/python
#-*- coding: utf-8 -*-
from sys import argv
from numpy import *
from numpy.random import *
from matplotlib.pyplot import *


def wykres(n):
    x_values = zeros(n)
    y_values = zeros(n)
    circ_size= zeros(n)
    point_numbers = range(n)
    for i in range(n - 1):
        x_values[i + 1] = x_values[i] + randn()
        y_values[i + 1] = y_values[i] + x_values[i]
        circ_size[i + 1]=circ_size[i]+ x_values[i]
    scatter(point_numbers, y_values, circ_size, c='yellow')
    axis('off')
    show()
    
wykres(666)

x=0
y=0
for x in range(-10, 10):
     y = 2*x*x + 2*x + 2
     print(f"X, Y: {x, y}")


x1=linspace(-10, 10)
y1 = 2*x1*x1 + 2*x1 + 2
plot(x1,y1)
#show()
def factorial(fac):
    if(ins==0):
        fac=1
    n=fac
    fac=1
    for i in range (1, int(n+1)):
        fac=fac*i
    print("urs factorial: ")
    print(int(fac))
    
ins=float(input("insert value, u gona get factorial of it "))
if(ins<0 or ins>0 and ins<1):
    print("Try with something natural and biger or equal 1")
else:
    factorial(ins)
        
        def lst (tab):
    mini=tab [0]
    for x in tab:
        if mini>x:
            mini=x
    for i in range(len(tab)):
        if(tab[i]==mini):
            print(mini, i)              
    print("Lst val and idx of it:")
    return (0)
argray=[]
print("Give me array, get lst val of it  ")
n=int(input("How many var?"))
for i in range(n):
    x=int(input())
    argray.append(x)
lst(argray)
